ln -sf ~/dotfiles/.Xresources ~/.Xresources
ln -sf ~/dotfiles/.xinputrc ~/.xinputrc
ln -sf ~/dotfiles/.xsessionrc ~/.xsessionrc
ln -sf ~/dotfiles/.config/dunst ~/.config/dunst
ln -sf ~/dotfiles/.config/fontconfig ~/.config/fontconfig
ln -sf ~/dotfiles/.config/i3 ~/.config/i3
ln -sf ~/dotfiles/.config/i3status ~/.config/i3status
ln -sf ~/dotfiles/.config/ranger ~/.config/ranger
ln -sf ~/dotfiles/bin ~/bin
ln -sf ~/dotfiles/.bash_profile ~/.bash_profile
